# Generated by Django 4.1.6 on 2023-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_menu_image_alter_restaurant_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", 0)), name="price_gt_0"
            ),
        ),
    ]
