# Generated by Django 4.1.6 on 2023-02-14 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_menu_price_gt_0"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="menu",
            name="price_gt_0",
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gt", 0)), name="min_price"
            ),
        ),
    ]
