# Generated by Django 4.1.6 on 2023-02-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_remove_menu_price_gt_0_alter_menu_price_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(fields=["name"], name="management__name_eadf38_idx"),
        ),
        migrations.AddIndex(
            model_name="menu",
            index=models.Index(fields=["type"], name="management__type_7c33c8_idx"),
        ),
    ]
